<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>2</version>
	<uuid>b5445ec1-8512-41db-a3fc-a59bfdc601d6</uuid>
	<name>Goal Plot 1</name>
	<type>3</type>
	<res_file_key>500d9636-2ba2-4af2-a1ac-40beb3bc8180</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<palette>
		<uuid>72583a8c-1759-47f5-87f9-d342def5e8b4</uuid>
		<parameter>
			<uuid/>
			<name/>
			<unit>0</unit>
			<formula/>
			<formula2/>
			<formula3/>
			<locality>0</locality>
		</parameter>
		<param_min>
			<value>0</value>
			<is_initialized>false</is_initialized>
			<is_global>true</is_global>
			<is_plot>false</is_plot>
		</param_min>
		<param_max>
			<value>0</value>
			<is_initialized>false</is_initialized>
			<is_global>true</is_global>
			<is_plot>false</is_plot>
		</param_max>
		<cs_uuid/>
		<cs_xform>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</cs_xform>
		<color_palette>5</color_palette>
		<ncolors>10</ncolors>
		<outer_minmax_coloring>0</outer_minmax_coloring>
		<outer_min_color>16711680</outer_min_color>
		<outer_max_color>255</outer_max_color>
		<outer_colors_display>false</outer_colors_display>
		<logarithmic>false</logarithmic>
		<custom_params_maxs/>
		<custom_params_mins/>
		<cs_name/>
		<display_plot_names>true</display_plot_names>
		<display_plot_minmaxes>false</display_plot_minmaxes>
		<display_title>false</display_title>
		<title/>
		<auto_scale_font>false</auto_scale_font>
		<use_default_font>true</use_default_font>
		<font>
			<name/>
			<size>9</size>
			<color>0</color>
			<font_isbold>false</font_isbold>
			<font_isitalic>false</font_isitalic>
		</font>
		<bkgd_color>16777215</bkgd_color>
		<bkgd_transp>1</bkgd_transp>
		<x>0</x>
		<y>0</y>
		<width>20</width>
		<height>200</height>
		<auto_ticks>true</auto_ticks>
		<ticks_number>11</ticks_number>
		<vertical>3</vertical>
		<rot_text>false</rot_text>
		<is_user_pos>false</is_user_pos>
	</palette>
	<chart>GG Force (Y) 1</chart>
	<minmax>
		<x_min>
			<value>0</value>
			<fit>true</fit>
		</x_min>
		<x_max>
			<value>0</value>
			<fit>true</fit>
		</x_max>
		<y_min>
			<value>0</value>
			<fit>true</fit>
		</y_min>
		<y_max>
			<value>0</value>
			<fit>true</fit>
		</y_max>
	</minmax>
	<appearance>
		<font>
			<name>Arial</name>
			<size>9</size>
			<color>0</color>
			<font_isbold>false</font_isbold>
			<font_isitalic>false</font_isitalic>
		</font>
		<use_default_font>true</use_default_font>
		<transparency>1</transparency>
		<background_color>0</background_color>
		<position>
			<item>395</item>
			<item>373</item>
			<item>1015</item>
			<item>663</item>
		</position>
		<scale_color>6579300</scale_color>
		<display_plot_names>true</display_plot_names>
	</appearance>
	<use_all_faces>false</use_all_faces>
	<geom_ref/>
	<group_by_param>false</group_by_param>
	<abscissa>1</abscissa>
	<goal_name/>
	<goal_uuid/>
	<goal_data>
		<item>
			<map_key>b288bdd5-d3dd-4023-b0da-8d196eb5f697</map_key>
			<formula/>
			<unit>7</unit>
			<goal_ui_order>0</goal_ui_order>
		</item>
		<item>
			<map_key>61cc3623-814c-4519-9928-1af714da7cf9</map_key>
			<formula>(2*4.18)/(1.225*(240*240)*0.00076841)</formula>
			<unit>42</unit>
			<goal_ui_order>1</goal_ui_order>
		</item>
	</goal_data>
	<unit_definition>
		<item>
			<map_key>7</map_key>
			<unit_def_custom_name/>
			<unit_def_custom_si_to_unit/>
			<unit_def_custom_unit_to_si/>
			<unit_def_precision>3</unit_def_precision>
			<unit_def_system>1100</unit_def_system>
		</item>
		<item>
			<map_key>42</map_key>
			<unit_def_custom_name/>
			<unit_def_custom_si_to_unit/>
			<unit_def_custom_unit_to_si/>
			<unit_def_precision>0</unit_def_precision>
			<unit_def_system>10001</unit_def_system>
		</item>
	</unit_definition>
	<goal_data_eq_goals_present>true</goal_data_eq_goals_present>
	<iteration>-1</iteration>
	<time>-1</time>
	<limit_by_iter>true</limit_by_iter>
	<limit_iter>105</limit_iter>
	<display>0</display>
	<callout>
		<position_initialized>2</position_initialized>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
		<2d_position>
			<item>705</item>
			<item>518</item>
		</2d_position>
		<visibility>true</visibility>
		<appearance>
			<title>true</title>
			<title_source>0</title_source>
			<use_default_font>true</use_default_font>
			<font>
				<name>Arial</name>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<value_color>16777215</value_color>
			<title_color>11711154</title_color>
			<line_color>0</line_color>
			<auto_line_color>true</auto_line_color>
			<transparency>0</transparency>
			<pinned>false</pinned>
			<show_results>true</show_results>
		</appearance>
	</callout>
</feature>
