<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>44cb1fed-6137-4e63-96f9-87ccfe01c589</uuid>
	<name>Points</name>
	<type>19</type>
	<res_file_key>5920df63-6ea1-4df9-9de7-18c59ae1baa1</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>true</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>a4b1300e-d41a-4a64-990b-3d7449911698</uuid>
			<name>Right Plane</name>
			<type>0</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>101</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>85c4e3c6-cbc1-4004-90d8-51380cbca6f8</geom_stamp_uuid>
			<origin>
				<item>-0.020220368493164664</item>
				<item>0</item>
				<item>-0.0596760151726064</item>
			</origin>
			<normal>
				<item>0</item>
				<item>1</item>
				<item>0</item>
			</normal>
			<vector>
				<item>-1</item>
				<item>-0</item>
				<item>-0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>-0.82083067979820235</min>
			<max>2.8801091176702709</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<point/>
	<points_def_mode>0</points_def_mode>
	<purpose>0</purpose>
	<points_table_def_mode>0</points_table_def_mode>
	<points_analytic_def_mode>0</points_analytic_def_mode>
	<points_analytic_def_line>
		<p1>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</p1>
		<p2>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</p2>
	</points_analytic_def_line>
	<points_analytic_def_rect>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<normal>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</normal>
		<up>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</up>
		<width>0</width>
		<height>0</height>
	</points_analytic_def_rect>
	<points_analytic_def_sphere>
		<center>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</center>
		<radius>0</radius>
	</points_analytic_def_sphere>
	<points_count>20</points_count>
	<points_spacing>0.02</points_spacing>
	<use_mesh_based_point_generation>false</use_mesh_based_point_generation>
	<file_path/>
	<file_time>0</file_time>
	<media>false</media>
</feature>
