<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>392f0f29-467c-45d8-ad6d-ff0f0f1d0bb9</uuid>
	<name>Cut Plot 2 Geometry</name>
	<type>14</type>
	<res_file_key>daa3dbb4-4944-404d-8a1f-e422b1b741c4</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>true</use_cad_geom>
	<moving_reference>false</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>dbb0eafb-c589-471a-9607-c645c76cd1f2</uuid>
			<name>Top Plane</name>
			<type>0</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>101</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>27c826d7-3ba9-4a34-bce7-f8279799f49d</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>-1.0999999999999996</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>1</item>
			</normal>
			<vector>
				<item>0</item>
				<item>1</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>-0.74336546222773736</min>
			<max>0.62401343188252456</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<domain_filter>
		<enabled>false</enabled>
		<keep>true</keep>
		<type>0</type>
		<domains/>
	</domain_filter>
	<medias>
		<item>1</item>
	</medias>
</feature>
