<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>fac7aad7-f1c1-4fec-a57e-e3c836687923</uuid>
	<name>Mesh 1</name>
	<type>12</type>
	<res_file_key>8adbc13e-7f9e-443f-9c99-58a283434ff8</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<box>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
		<item>nan</item>
	</box>
	<crop_region_anchors>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
	</crop_region_anchors>
	<section_plane/>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>97c16706-a974-4034-8180-d6fc791d4360</uuid>
			<name>Right Plane</name>
			<type>0</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>101</update_stamp>
			<group>1</group>
			<geom_stamp_uuid>1793a4eb-4254-48bb-bb9c-5a5db9fd71b0</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>0.0098786136190089809</item>
				<item>0.020243820522474705</item>
			</origin>
			<normal>
				<item>1</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>-0</item>
				<item>-0</item>
				<item>-1</item>
			</vector>
			<pos>0.0067788971093602438</pos>
			<flip>1</flip>
			<min>-0.060979938822428852</min>
			<max>0.080979967519430124</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<section_def_mode>0</section_def_mode>
	<xyz_plane>0</xyz_plane>
	<points>
		<item>500</item>
		<item>500</item>
		<item>400</item>
		<item>400</item>
	</points>
	<camera>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<up>
			<item>0</item>
			<item>1</item>
			<item>0</item>
		</up>
		<direction>
			<item>0</item>
			<item>0</item>
			<item>-1</item>
		</direction>
		<scale>1</scale>
	</camera>
	<display>0</display>
	<cut_with_section>false</cut_with_section>
	<section_medias>
		<item>1</item>
	</section_medias>
	<mesh_type>0</mesh_type>
	<surface_media>1</surface_media>
	<MeshTypePriority>0</MeshTypePriority>
	<MediaPriority>1</MediaPriority>
	<contours>
		<display>true</display>
		<palette>
			<uuid>07ba07f2-14a8-4a77-b7c8-cee97d4b87da</uuid>
			<parameter>
				<uuid>46096123-A86C-43c8-B809-DB1C7CB2E6AA</uuid>
				<name>Refinement level</name>
				<unit>72</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>1</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs>
				<46096123-A86C-43c8-B809-DB1C7CB2E6AA>
					<value>1</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</46096123-A86C-43c8-B809-DB1C7CB2E6AA>
			</custom_params_maxs>
			<custom_params_mins>
				<46096123-A86C-43c8-B809-DB1C7CB2E6AA>
					<value>0</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</46096123-A86C-43c8-B809-DB1C7CB2E6AA>
			</custom_params_mins>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name>Arial</name>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>439</x>
			<y>38</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>true</is_user_pos>
		</palette>
		<color_by_param>true</color_by_param>
		<color>0</color>
	</contours>
	<mesh>
		<display>true</display>
		<color>0</color>
	</mesh>
	<cell_mode>0</cell_mode>
	<color>62207</color>
	<aspect>10</aspect>
	<percentage>0.20000000000000001</percentage>
	<channels>
		<palette>
			<uuid>0f85a574-f294-4370-b92c-c0f18a893a07</uuid>
			<parameter>
				<uuid>FFB784BF-E692-40E4-AF7C-D8CE07F6C372</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>2.5683507747395032e-06</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0.16785984360496001</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>2</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs>
				<FFB784BF-E692-40E4-AF7C-D8CE07F6C372>
					<value>0.16785984360496001</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</FFB784BF-E692-40E4-AF7C-D8CE07F6C372>
			</custom_params_maxs>
			<custom_params_mins>
				<FFB784BF-E692-40E4-AF7C-D8CE07F6C372>
					<value>2.5683507747395032e-06</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</FFB784BF-E692-40E4-AF7C-D8CE07F6C372>
			</custom_params_mins>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<mesh>true</mesh>
		<color>0</color>
		<interpolate>true</interpolate>
	</channels>
</feature>
