<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>c219fde7-3e57-4715-99e7-40ea4276aded</uuid>
	<name>Cut Plot 2</name>
	<type>0</type>
	<res_file_key>da9464b8-893b-47ed-ae74-b9ef04a09328</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>true</use_cad_geom>
	<moving_reference>false</moving_reference>
	<moving_display>false</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<box>
		<item>-0.59999999999999998</item>
		<item>0.59999999999999998</item>
		<item>-5.0999999999999996</item>
		<item>2.8999999999999999</item>
		<item>-0.74336546222773736</item>
		<item>0.62401343188252456</item>
	</box>
	<crop_region_anchors>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
	</crop_region_anchors>
	<section_plane/>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>dbb0eafb-c589-471a-9607-c645c76cd1f2</uuid>
			<name>Top Plane</name>
			<type>0</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>101</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>27c826d7-3ba9-4a34-bce7-f8279799f49d</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>-1.0999999999999996</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>1</item>
			</normal>
			<vector>
				<item>0</item>
				<item>1</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>-0.74336546222773736</min>
			<max>0.62401343188252456</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<domain_filter>
		<enabled>false</enabled>
		<keep>true</keep>
		<type>0</type>
		<domains/>
	</domain_filter>
	<contours>
		<display>true</display>
		<palette>
			<uuid>d349721b-1c03-4d6b-a66d-7127573372b7</uuid>
			<parameter>
				<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
				<name>Pressure</name>
				<unit>14</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>89290.949618156475</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>232603.37465561158</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs>
				<65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
					<value>70.922846655592068</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
				<88A4B00C-3C32-4822-94C2-4682145D4F95>
					<value>238572.59674452757</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</88A4B00C-3C32-4822-94C2-4682145D4F95>
			</custom_params_maxs>
			<custom_params_mins>
				<65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
					<value>-266.60767193471685</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
				<88A4B00C-3C32-4822-94C2-4682145D4F95>
					<value>63236.603921027978</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</88A4B00C-3C32-4822-94C2-4682145D4F95>
			</custom_params_mins>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name>Arial</name>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>390</x>
			<y>38</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>true</is_user_pos>
		</palette>
		<color_by_param>true</color_by_param>
		<color>16711680</color>
	</contours>
	<min_callout>
		<display>false</display>
		<coordinates>false</coordinates>
		<appearance>
			<title>true</title>
			<title_source>0</title_source>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<value_color>16777215</value_color>
			<title_color>16758122</title_color>
			<line_color>0</line_color>
			<auto_line_color>true</auto_line_color>
			<transparency>0</transparency>
			<pinned>false</pinned>
			<show_results>true</show_results>
		</appearance>
		<position_initialized>false</position_initialized>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
	</min_callout>
	<max_callout>
		<display>false</display>
		<coordinates>false</coordinates>
		<appearance>
			<title>true</title>
			<title_source>0</title_source>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<value_color>16777215</value_color>
			<title_color>8026879</title_color>
			<line_color>0</line_color>
			<auto_line_color>true</auto_line_color>
			<transparency>0</transparency>
			<pinned>false</pinned>
			<show_results>true</show_results>
		</appearance>
		<position_initialized>false</position_initialized>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
	</max_callout>
	<isolines>
		<display>false</display>
		<palette>
			<uuid>e29a958b-e9e1-4ba3-a98e-f9bd82797611</uuid>
			<parameter>
				<uuid>65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C</uuid>
				<name>Velocity (Y)</name>
				<unit>19</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>-252.28376654948366</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>71.909637805263159</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs>
				<65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
					<value>71.909637805263159</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
				<88A4B00C-3C32-4822-94C2-4682145D4F95>
					<value>239117.30264893934</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</88A4B00C-3C32-4822-94C2-4682145D4F95>
			</custom_params_maxs>
			<custom_params_mins>
				<65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
					<value>-252.28376654948366</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
				<88A4B00C-3C32-4822-94C2-4682145D4F95>
					<value>77907.040145983134</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</88A4B00C-3C32-4822-94C2-4682145D4F95>
			</custom_params_mins>
			<cs_name>Global Coordinate System</cs_name>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name>Arial</name>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>687</x>
			<y>668</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>true</is_user_pos>
		</palette>
		<width>1</width>
		<color_by_param>true</color_by_param>
		<color>0</color>
	</isolines>
	<vectors>
		<display>false</display>
		<build_palette>
			<uuid>803e7d75-8f8e-4780-91f2-340559e5a2cd</uuid>
			<parameter>
				<uuid>8A88FD9A-C36E-4151-864A-F5BC1C916074</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</build_palette>
		<palette>
			<uuid>e29a958b-e9e1-4ba3-a98e-f9bd82797611</uuid>
			<parameter>
				<uuid>65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C</uuid>
				<name>Velocity (Y)</name>
				<unit>19</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>-252.28376654948366</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>71.909637805263159</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs>
				<65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
					<value>71.909637805263159</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
				<88A4B00C-3C32-4822-94C2-4682145D4F95>
					<value>239117.30264893934</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</88A4B00C-3C32-4822-94C2-4682145D4F95>
			</custom_params_maxs>
			<custom_params_mins>
				<65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
					<value>-252.28376654948366</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
				<88A4B00C-3C32-4822-94C2-4682145D4F95>
					<value>77907.040145983134</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</88A4B00C-3C32-4822-94C2-4682145D4F95>
			</custom_params_mins>
			<cs_name>Global Coordinate System</cs_name>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name>Arial</name>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>687</x>
			<y>668</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>true</is_user_pos>
		</palette>
		<color_by_param>false</color_by_param>
		<color>0</color>
		<vectors_projected>true</vectors_projected>
		<arrow_size>0.040000000000000001</arrow_size>
		<spacing>0.040000000000000001</spacing>
		<minmax_arrowsize_ratio>0.001</minmax_arrowsize_ratio>
		<logarithmic_arrows>false</logarithmic_arrows>
		<vistype>0</vistype>
		<dynamic>
			<enabled>true</enabled>
			<width>6</width>
			<arrow_size>32</arrow_size>
			<spacing>8</spacing>
		</dynamic>
	</vectors>
	<essslic>
		<display>false</display>
		<build_palette>
			<uuid>2cdf5933-c190-421e-bf62-9dda023d4fd0</uuid>
			<parameter>
				<uuid>8A88FD9A-C36E-4151-864A-F5BC1C916074</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</build_palette>
		<palette>
			<uuid>e29a958b-e9e1-4ba3-a98e-f9bd82797611</uuid>
			<parameter>
				<uuid>65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C</uuid>
				<name>Velocity (Y)</name>
				<unit>19</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>-252.28376654948366</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>71.909637805263159</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs>
				<65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
					<value>71.909637805263159</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
				<88A4B00C-3C32-4822-94C2-4682145D4F95>
					<value>239117.30264893934</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</88A4B00C-3C32-4822-94C2-4682145D4F95>
			</custom_params_maxs>
			<custom_params_mins>
				<65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
					<value>-252.28376654948366</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C>
				<88A4B00C-3C32-4822-94C2-4682145D4F95>
					<value>77907.040145983134</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</88A4B00C-3C32-4822-94C2-4682145D4F95>
			</custom_params_mins>
			<cs_name>Global Coordinate System</cs_name>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name>Arial</name>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>687</x>
			<y>668</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>true</is_user_pos>
		</palette>
		<color_by_param>false</color_by_param>
		<color>0</color>
		<vistype>0</vistype>
		<esss_vistype>0</esss_vistype>
		<esss_linespacing>12</esss_linespacing>
		<esss_linewidth>2</esss_linewidth>
		<lic_noisegrainsize>1</lic_noisegrainsize>
		<lic_noisedensity>0.5</lic_noisedensity>
		<lic_contrast>0.10000000000000001</lic_contrast>
		<lic_convsize>64</lic_convsize>
	</essslic>
	<mesh>
		<display>false</display>
		<color>0</color>
	</mesh>
	<background>
		<display>false</display>
		<color>16777215</color>
	</background>
	<outlines_display>true</outlines_display>
	<outlines_color>0</outlines_color>
	<DeformedShape>
		<uuid>407a0aeb-2042-45de-84a2-3018e255b4f1</uuid>
		<creation_date>1783732435</creation_date>
		<enabled>false</enabled>
		<auto_scale>true</auto_scale>
		<scale/>
		<mode>-1</mode>
	</DeformedShape>
	<medias>
		<item>1</item>
	</medias>
	<mesh_type>0</mesh_type>
	<MeshTypePriority>0</MeshTypePriority>
	<section_def_mode>0</section_def_mode>
	<xyz_plane>0</xyz_plane>
	<points>
		<item>500</item>
		<item>500</item>
		<item>400</item>
		<item>400</item>
	</points>
	<camera>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<up>
			<item>0</item>
			<item>1</item>
			<item>0</item>
		</up>
		<direction>
			<item>0</item>
			<item>0</item>
			<item>-1</item>
		</direction>
		<scale>1</scale>
	</camera>
	<profile>
		<enabled>false</enabled>
		<grid>false</grid>
		<grid_step>0.01</grid_step>
		<bumpsize>0.10000000000000001</bumpsize>
	</profile>
	<isolines_displayvalues>false</isolines_displayvalues>
	<vectors_uniformmesh>true</vectors_uniformmesh>
	<media>1</media>
</feature>
