<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid/>
	<name>Global Min/Max: Velocity (Y)</name>
	<type>13</type>
	<res_file_key>033a7258-7160-4d85-8261-7c8f69f08900</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<parameter>
		<uuid>65CC5BC2-D735-4a6e-928A-EEB9EF5DD43C</uuid>
		<name>Velocity (Y)</name>
		<unit>19</unit>
		<formula/>
		<formula2/>
		<formula3/>
		<locality>0</locality>
	</parameter>
</feature>
