<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid/>
	<name>Global Min/Max: Channel Height</name>
	<type>13</type>
	<res_file_key>df205d01-94d2-41c6-93b3-94828f1003eb</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<parameter>
		<uuid>FFB784BF-E692-40E4-AF7C-D8CE07F6C372</uuid>
		<name>Channel Height</name>
		<unit>10</unit>
		<formula/>
		<formula2/>
		<formula3/>
		<locality>0</locality>
	</parameter>
</feature>
